---


- name: Start the Firewall Daemon and enable automatic startup
  shell: "systemctl {{ item }} firewalld.service"
  with_items:
    - start
    - enable
  tags:
   - start
   - enable
   - firewall
   - daemon
   - systemctl


- name: Allow HTTP Access through Firewall
  shell: "{{ item }}"
  with_items:
    - "firewall-cmd --permanent --zone=public --add-service=http"
    - "systemctl restart firewalld.service"
  tags:
   - allow
   - http
   - firewall
   - daemon
   - systemctl


- name: Start Apache HTTP Daemon and enable automatic startup
  shell: "systemctl {{ item }} httpd.service"
  with_items:
    - start
    - enable
  tags:
   - start
   - enable
   - http
   - daemon
   - systemctl
